modLoader="javafml"
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]]
modId="mmorpg" 
version="${file.jarVersion}" 
displayName="MMORPG Mod" 
description='''
'''
[[dependencies.mmorpg]] 
    modId="forge"
    mandatory=true 
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
